// Mocks generated by Mockito 5.0.17 from annotations
// in rick_and_morty/test/features/characters/presentation/bloc/characters/characters_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rick_and_morty/core/error/failures.dart' as _i6;
import 'package:rick_and_morty/core/use_cases/use_case.dart' as _i8;
import 'package:rick_and_morty/features/characters/domain/entities/character.dart'
    as _i7;
import 'package:rick_and_morty/features/characters/domain/entities/series.dart'
    as _i10;
import 'package:rick_and_morty/features/characters/domain/repositories/characters_repository.dart'
    as _i2;
import 'package:rick_and_morty/features/characters/domain/use_cases/get_characters.dart'
    as _i4;
import 'package:rick_and_morty/features/characters/domain/use_cases/get_series.dart'
    as _i9;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeCharactersRepository_0 extends _i1.Fake
    implements _i2.CharactersRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetCharacters].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCharacters extends _i1.Mock implements _i4.GetCharacters {
  MockGetCharacters() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CharactersRepository get repository => (super.noSuchMethod(
      Invocation.getter(#repository),
      returnValue: _FakeCharactersRepository_0()) as _i2.CharactersRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Character>>> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue:
                  Future<_i3.Either<_i6.Failure, List<_i7.Character>>>.value(
                      _FakeEither_1<_i6.Failure, List<_i7.Character>>()))
          as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Character>>>);
}

/// A class which mocks [GetSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSeries extends _i1.Mock implements _i9.GetSeries {
  MockGetSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CharactersRepository get repository => (super.noSuchMethod(
      Invocation.getter(#repository),
      returnValue: _FakeCharactersRepository_0()) as _i2.CharactersRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i10.Series>> call(_i8.NoParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i3.Either<_i6.Failure, _i10.Series>>.value(
                  _FakeEither_1<_i6.Failure, _i10.Series>()))
          as _i5.Future<_i3.Either<_i6.Failure, _i10.Series>>);
}
