// Mocks generated by Mockito 5.0.17 from annotations
// in rick_and_morty/test/features/characters/presentation/bloc/character/character_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rick_and_morty/core/error/failures.dart' as _i6;
import 'package:rick_and_morty/features/characters/domain/entities/character.dart'
    as _i7;
import 'package:rick_and_morty/features/characters/domain/repositories/characters_repository.dart'
    as _i2;
import 'package:rick_and_morty/features/characters/domain/use_cases/get_concrete_character.dart'
    as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeCharactersRepository_0 extends _i1.Fake
    implements _i2.CharactersRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetConcreteCharacter].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetConcreteCharacter extends _i1.Mock
    implements _i4.GetConcreteCharacter {
  MockGetConcreteCharacter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CharactersRepository get repository => (super.noSuchMethod(
      Invocation.getter(#repository),
      returnValue: _FakeCharactersRepository_0()) as _i2.CharactersRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Character>> call(_i4.Params? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i3.Either<_i6.Failure, _i7.Character>>.value(
                  _FakeEither_1<_i6.Failure, _i7.Character>()))
          as _i5.Future<_i3.Either<_i6.Failure, _i7.Character>>);
}
